def Initialize(*args, **kwargs): ...
def AuthenticateServiceAccount(*args, **kwargs): ...

class String:
    def __init__(self, *args, **kwargs): ...
    def getInfo(self): ...

class Image:
    def __init__(self, *args, **kwargs): ...
    def getInfo(self): ...

class FeatureCollection:
    def __init__(self, *args, **kwargs): ...
    def getInfo(self): ...
# ee.pyi
def Initialize(*args, **kwargs): ...
class String: 
    def __init__(self, *a, **k): ...
    def getInfo(self): ...
class Image: 
    def __init__(self, *a, **k): ...
    def getInfo(self): ...